repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.57.0
    hooks:
      - id: swiftlint
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.54.6
    hooks:
       - id: swiftformat
         args: [--config, .swiftformat, --quiet]
