name: format, lint, build and test

on:
    pull_request:
      branches:
      - main

jobs:
  build_project:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: SwiftFormat
        run: swiftformat . --lint
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: SwiftLint
        run: swiftlint lint --strict
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.app
      - name: Build Cleanup
        run: |
          xcodebuild clean -project skoda-tender-ios.xcodeproj -scheme skoda-tender-ios | xcpretty
      - name: Build Test
        run: |
          xcodebuild test -project skoda-tender-ios.xcodeproj -scheme skoda-tender-ios -destination 'platform=iOS   Simulator,name=iPhone 16 Pro Max,OS=18.0' | xcpretty -s

